; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[common]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_extra_dirs = ~/Documents/Arduino/libraries
lib_deps =
    adafruit/DHT sensor library
    adafruit/Adafruit Unified Sensor
lib_ignore = ArduinoHttpClient

; ── BASE (WiFi + Google Sheets) ──────────────────────────────
[env:base]
extends = common
build_flags = -DMEU_ID=0 -DBASE_ID=0

; ── NÓS SENSORES ─────────────────────────────────────────────
[env:node1]
extends = common
build_flags = -DMEU_ID=1 -DBASE_ID=0

[env:node2]
extends = common
build_flags = -DMEU_ID=2 -DBASE_ID=0

[env:node3]
extends = common
build_flags = -DMEU_ID=3 -DBASE_ID=0

[platformio]
description = ProjetofirmwareLoRa
default_envs = base
